### ISSUE TITLE
github contribution on about page

### ISSUE THREAD

**Issue by b1azk0** [ciflikli/website#1]
Hi there,
Ive been playing around with some settings of blogdown and came across your blog.
I wasn't able to find that in the source hence my question:
How did you add github contrib image to your "about" page?
Thanks for any hints,
regards!

**Comment by ciflikli** [comment]
Hi,

I got the script from [2016rshah](https://github.com/2016rshah/githubchart-api).

Basically, you just need to add

    <img src="http://ghchart.rshah.org/2016rshah" alt="2016rshah's Github chart" />

to your about.html section - don't forget to change ```2016rshah``` to your own GitHub name. Mine can be found [here](https://github.com/ciflikli/website/blob/master/themes/hugo-theme-cactus-plus/layouts/section/about.html).

**Comment by b1azk0** [comment]
Thank you :)

**Comment by b1azk0** [comment]
Sorry to bother you here, but I've spent the whole day looking for answers to other questions and feel i'm stuck. If you can help me out, I'd really appreciate.

1) How to change code blocks styling: yours has blue background and readable letters. Mine (out of the box) looks more as `highlight: zenburn` in typical Rmarkdown and (for me) it's completely unreadable
2) Add description to post  - instead of summary. I've played with some config.toml settings but with no luck
3) Add categories / tags under post title (just you do). In this case I also failed in finding where you did changes to default template settings.

If that's of any help my config files are located at: https://github.com/b1azk0/blog (site itself is not fully functioning due to DNS issues, but i'll fix that later).

In any case thank you for your time.
Greetings!

**Comment by ciflikli** [comment]
Hi, I will close this as they are not relevant to the original issue, but feel free to open new issues separately and I'll look into them.

**Comment by b1azk0** [comment]
sure thing. thank you
