### ISSUE TITLE
Code blocks styling

### ISSUE THREAD

**Issue by b1azk0** [ciflikli/website#2]
In order to keep things organized i'll ask fruther questions as separate issues:

1) How to change code blocks styling: yours has blue background and readable letters. Mine (out of the box) looks more as highlight: zenburn in typical Rmarkdown and (for me) it's completely unreadable

If that's of any help my config files are located at: https://github.com/b1azk0/blog (site itself is not fully functioning due to DNS issues, but i'll fix that later).

**Comment by ciflikli** [comment]
The code syntax was really difficult for me to get as well. I can direct you to the following:

The underlying code for thomasp85's [website](https://github.com/thomasp85/thomasp85.github.io) (where I got my inspiration).

My closed [issue#125](https://github.com/rstudio/blogdown/issues/125) with Yihui.

Hope these help.

**Comment by b1azk0** [comment]
This indeed looks complicated and I doubt I can follow those instructions with success.
I'll try to fork your entire website and see how that works with my rmd files, and if it doesn't I'll just leave highlighting as it is. Thank you
