### ISSUE TITLE
Description under post title

### ISSUE THREAD

**Issue by b1azk0** [ciflikli/website#3]
In order to keep things organized i'll ask fruther questions as separate issues:

2) Add description to post - instead of summary. I've played with some config.toml settings but with no luck

If that's of any help my config files are located at: https://github.com/b1azk0/blog (site itself is not fully functioning due to DNS issues, but i'll fix that later).

**Comment by ciflikli** [comment]
I'm not sure if that's what you mean, but when you create a .Rmd file, you can just add a post description to your post header with ```description: 'your description here'```.
 
Edit: Realised this after posting in [issue#4](https://github.com/ciflikli/website/issues/4); you might need to add:

    {{ .Title }} <h2>{{ .Description | markdownify }}</h2>

to your post-list.html.

**Comment by b1azk0** [comment]
works like a charm! thank you
