### ISSUE TITLE
Categories / tags under post title

### ISSUE THREAD

**Issue by b1azk0** [ciflikli/website#4]
In order to keep things organized i'll ask fruther questions as separate issues:

3) Add categories / tags under post title (just you do). In this case I also failed in finding where you did changes to default template settings.

If that's of any help my config files are located at: https://github.com/b1azk0/blog (site itself is not fully functioning due to DNS issues, but i'll fix that later).

**Comment by ciflikli** [comment]
I believe it is achieved by adding this to the [post-list.html](https://github.com/ciflikli/website/blob/master/themes/hugo-theme-cactus-plus/layouts/partials/post-list.html) (it's been a while since I designed the website):

    {{ partial "meta-terms.html" . }}

**Comment by b1azk0** [comment]
works like a charm! thank you
