### ISSUE TITLE
How do you make Github contribution in your personal website?

### ISSUE THREAD

**Issue by Zhenye-Na** [ciflikli/website#5]
Hi Gokhan,

Hope everything goes well. Recently I came across your personal website. I really love the layout of your website and admire your projects you did. However, I am new to 'website building', could you tell be how did you add the Github contribution in you "About" page?

Thank you!!

Best regards,
Zhenye Na

**Comment by ciflikli** [comment]
Hi Zhenye,

Please see closed issue #1

Best,

Gokhan
